### ISSUE TITLE
您好，这个项目什么时候完全开源

### ISSUE THREAD

**Issue by 26597925** [micro-in-cn/micro-web#1]
我看到gif上面很多功能都实现了，能否开源，如果能开源什么时候，能开放出来看看，谢谢！

**Comment by printfcoder** [comment]
hi，您好。项目会100%开源，该项目是从micro里剥离出来的，其实micro的三月份版本里已经有了，后来删掉了，主要是因为还有bug。现在第一步是剥离，下一步是插件化，然后是持久化各种追踪数据。第一阶段是保证与v1版本相同功能，大概会在一星期左右放出来。修复bug与二阶段随即开始。

因为控制台是all in one的，所以早晚会膨胀得比较重，甚至比micro还重，所以我们选择剥离。

**Comment by 26597925** [comment]
好的，谢谢。
